### ISSUE TITLE
pysimplesoap is not listed as a requirement

### ISSUE THREAD

**Issue by SimplicityGuy** [venthur/python-debianbts#28]
It's used within the module, but it's not listed as a requirement in setup.py. This causes pip installation (or upgrade) to fail.

Please list it in setup.py under `install_requires`.

**Comment by irl** [comment]
This is breaking the installation of bugwarrior with ralphbean/bugwarrior/pull/348.

The patch looks good to me.

**Comment by irl** [comment]
@venthur Can you please push that to PyPI?

**Comment by ntnn** [comment]
Just hit this as well while packaging bugwarrior and dependencies.
@venthur Please push the updated version to pypi as well.

**Comment by venthur** [comment]
Done.
