### ISSUE TITLE
get_bugs does not support use of proxy

### ISSUE THREAD

**Issue by kaymccormick** [venthur/python-debianbts#41]
See [debian bug #914057](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=914057).

reportbug is unable to pass http proxy handling information to debianbts get_bugs because there is no mechanism to supply the proxy information. This is blocking resolution of [debian bug #717563](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=717563) in package reportbug.

Someone suggested to use the following python code prior to making calls into debianbts:

> debianbts._soap_client_kwargs['proxy'] = http_proxy

However, this does not seem like the correct approach since there should be an interface or function to supply this information, either directly on get_bugs and related functions, or a soap client initialization function. I am guessing a separate "soap client initialization function" is maybe the best approach?

Please advise

**Comment by kaymccormick** [comment]
In trying to fix this, I installed latest pysimplesoap, and got the following message:

python-debianbts 2.7.3 has requirement pysimplesoap!=1.16.2, but you'll have pysimplesoap 1.16.2 which is incompatible.

It seems problematic if the latest version of python-debianbts cannot use the latest version of pysimplesoap, because this probably blocks bugfixes ?

**Comment by kaymccormick** [comment]
I added a message to the bug [https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=717563](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=717563) including patches for reportbug and python-debianbts. I need to do more work and testing on the changes.

**Comment by venthur** [comment]
Fixed by recent merge. Thanks!
