### ISSUE TITLE
Pysimplesoap Maintenance Status

### ISSUE THREAD

**Issue by ryneeverett** [venthur/python-debianbts#59]
It looks like no maintainer has reviewed a pull request on [pysimplesoap](https://github.com/pysimplesoap/pysimplesoap) for since July 2020 which is over 3 years ago. Thus, despite 3 pull requests in the last year (https://github.com/pysimplesoap/pysimplesoap/pull/204, https://github.com/pysimplesoap/pysimplesoap/pull/206, https://github.com/pysimplesoap/pysimplesoap/pull/210), it still doesn't have python-3.11 support.

Thus in [bugwarrior](https://github.com/ralphbean/bugwarrior) we're getting traces like:

```
 bugwarrior/services/bts.py:1: in <module>
    import debianbts
/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/debianbts/__init__.py:1: in <module>
    from debianbts.debianbts import *  # noqa
/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/debianbts/debianbts.py:22: in <module>
    from pysimplesoap.client import SoapClient
/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/pysimplesoap/__init__.py:16: in <module>
    from . import client, server, simplexml, transport
/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/pysimplesoap/client.py:33: in <module>
    from .transport import get_http_wrapper, set_http_wrapper, get_Http
/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/pysimplesoap/transport.py:107: in <module>
    if 'timeout' in inspect.getargspec(httplib2.Http.__init__)[0]:
E   AttributeError: module 'inspect' has no attribute 'getargspec'
```

One option would of course be to fork/patch pysimplesoap, but given the maintenance status I wonder if it would make more sense to switch python-debianbts to a more actively developed client such as [zeep](https://github.com/mvantellingen/python-zeep)?

**Comment by venthur** [comment]
I agree, migration to another SOAP library probably makes most sense here. I looked at zeep, it is available in debian, which is very good, however the last commit to the repository is almost a year old. Are there any alternatives?

**Comment by ryneeverett** [comment]
I see that similar issues are arising in zeep about python-3.12 so zeep's maintenance status is indeed a concern.

However, I think zeep is more likely to be maintained than pysimplesoap because it is more widely used. I don't know how to make a similar query in Debian, but in Nix zeep is a dependency of about 10 packages while pysimplesoap is only a dependency of python-debianbts. If the current maintainers don't step up it seems likely that distributions would develop authoritative patches at first and eventually select a zeep fork.

I don't think there are any better maintained python SOAP clients than zeep. Alternatives would be for you to recommend a pysimplesoap fork, develop your own, or vendor it into python-debianbts.

**Comment by venthur** [comment]
Newest version does not depend anymore on any external SOAP library.
